# Generated by Django 4.1.4 on 2022-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('Asset', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Allocation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyTopPerformers',
            fields=[
                ('walletAddress', models.CharField(max_length=30)),
                ('Asset', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopPerformerWalletPerformance',
            fields=[
                ('time', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
