# Generated by Django 4.1.4 on 2022-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0002_rename_topperformerwalletperformance_topperformancegraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomGroupName', models.CharField(max_length=30)),
                ('timeFrame', models.CharField(max_length=30)),
            ],
        ),
    ]
