# Generated by Django 4.1.4 on 2022-12-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0003_topperformer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenName', models.CharField(max_length=30)),
                ('tokenAbbreviation', models.CharField(max_length=30)),
                ('AmountInEth', models.FloatField()),
                ('tokenAllocation', models.FloatField()),
                ('AmountInEthUSD', models.FloatField()),
                ('changeInTokenPrice', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
