# Generated by Django 4.1.4 on 2022-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0004_assettable_delete_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTopPerformanceGraph',
            fields=[
                ('time', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendingTopPerformers',
            fields=[
                ('walletAddress', models.CharField(max_length=30)),
                ('Asset', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('growth', models.FloatField()),
                ('growthChange', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='dailytopperformers',
            old_name='balance',
            new_name='growth',
        ),
        migrations.AddField(
            model_name='dailytopperformers',
            name='growthChange',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
