# Generated by Django 4.1.4 on 2022-12-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0007_rename_topperformer_topperformerconnections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopPerformerConnections',
            new_name='OverviewConnections',
        ),
    ]
