# Generated by Django 4.1.4 on 2022-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0010_alter_overviewconnections_timeframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytopperformers',
            name='walletAddress',
            field=models.CharField(max_length=50),
        ),
    ]
