# Generated by Django 4.1.4 on 2022-12-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0013_alter_profileconnections_walletid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconnections',
            name='walletID',
            field=models.CharField(default='awaitingConnections', max_length=50),
        ),
        migrations.AlterField(
            model_name='trendingtopperformers',
            name='walletAddress',
            field=models.CharField(max_length=50),
        ),
    ]
