# Generated by Django 4.1.4 on 2022-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0014_alter_profileconnections_walletid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltopperformancegraph',
            name='time',
            field=models.CharField(default='1H', max_length=30, primary_key=True, serialize=False),
        ),
    ]
