# Generated by Django 4.1.4 on 2022-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0015_alter_personaltopperformancegraph_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltopperformancegraph',
            name='time',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
