# Generated by Django 4.1.4 on 2022-12-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0016_alter_personaltopperformancegraph_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconnections',
            name='walletID',
            field=models.CharField(default='0xa542f325990CEB47e2AE8BD9dccF8960b16eB7a9', max_length=50),
        ),
    ]
