# Generated by Django 4.1.4 on 2022-12-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0019_alter_profileconnections_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconnections',
            name='roomGroupName',
            field=models.CharField(max_length=30),
        ),
    ]
