# Generated by Django 4.1.4 on 2022-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0020_alter_profileconnections_roomgroupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconnections',
            name='walletID',
            field=models.CharField(max_length=50),
        ),
    ]
