# Generated by Django 4.1.4 on 2023-01-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0022_test'),
    ]

    operations = [
    ]
