# Generated by Django 4.1.4 on 2023-01-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0023_toshi'),
    ]

    operations = [
        migrations.CreateModel(
            name='historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=240, verbose_name='Name')),
                ('date', models.CharField(max_length=240, verbose_name='Name')),
                ('price', models.FloatField()),
            ],
        ),
    ]
