# Generated by Django 4.1.4 on 2023-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0024_historic'),
    ]

    operations = [
        migrations.CreateModel(
            name='coinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=240, verbose_name='identification')),
                ('symbol', models.CharField(max_length=240, verbose_name='symbol')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='historic',
            name='date',
            field=models.CharField(max_length=240, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='token',
            field=models.CharField(max_length=240, verbose_name='token'),
        ),
    ]
