# Generated by Django 4.1.4 on 2023-01-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0027_contractlist_remove_coinlist_contractaddress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contractList',
            new_name='contracts',
        ),
    ]
