# Generated by Django 4.1.4 on 2023-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshi', '0028_rename_contractlist_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='coinImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=240, verbose_name='identification')),
                ('image_url', models.CharField(max_length=240, verbose_name='image_url')),
            ],
        ),
    ]
