# Generated by Django 4.1.4 on 2023-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toshi", "0029_coinimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryConnections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomGroupName", models.CharField(max_length=30)),
                ("walletID", models.CharField(max_length=50)),
            ],
        ),
    ]
